### ISSUE TITLE
Want to be able to transfer file from PC to SB via wifi

### ISSUE THREAD

**Issue by Neex101** [YetiTool/console-raspi3b-plus-platform#2] opened 2019-02-23 18:04 UTC
Need mechanism available on platform. Mr T can you advise?

Option 1: FTP (as previously proven from python script in Fusion 360, didn' have any dependencies)
Option 2:  pscp "C:\Users\Ed\Desktop\YETI temp\Rack cut files\yTeeth2.nc" pi@192.168.0.72:/home/pi/easycut-smartbench/src/jobCache/  --- (think this had dependency)

**Comment by Klazomenai** [comment] 2019-03-27 19:51
Duplicate of #5 
Closing

**Closed as completed by Klazomenai** 2019-03-27 19:51 UTC
